### ISSUE TITLE
Activation of extension breaks pagination

### ISSUE THREAD

**Issue by shortmort37** [phpBB-Studio/TopicCementStyle#2]
**Describe the bug**
Forums contain lists of topics, up to the board's setting of "topics per page" (TPP).  Forums go to multiple pages when TPP is exceeded.

With this extension disabled, a forum with more topics than TPP accurately displays all of the topics for selection.  With this extension enabled - and *without* assigning topic priorities, or any other features of the extension - the topics presented on subsequent pages are those of the first page.  The topics that should be there are not obliterated, they are just not present for selection.

**To Reproduce**
I created a new forum here:  http://59plymouth.net/59test/viewforum.php?f=120

I then entered 25 topics sequentially, starting with 1, and ending with 25.  Both the title and the content of the topic are the number.  My TPP is 20.

With the extension disabled, the first page shows topics 25-6 in descending order; the second, topics 5-1 in descending order.  This is expected behavior.

With the extension enabled, the first page displays as above.  However, the second page displays topics 21-25 - now, in ascending order.

**Expected behavior**
Enabling this extension should not permute the order of the topics, if they all have a default priority of 0 (zero).

**Screenshots**
Page 2 with extension disabled:
![disabled](https://user-images.githubusercontent.com/10282646/81243520-14a39d00-8fde-11ea-9c26-6e5ada92c8c0.JPG)
Page 2 with extension enabled:
![enabled](https://user-images.githubusercontent.com/10282646/81243552-238a4f80-8fde-11ea-9d03-fa8bc5482452.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Chrome 81.0.4044.138

**Additional context**
This behavior is exhibited with V3.3.0 of phpBB.  Per the author's recommendation, I edited ext.php to permit the extension to load.  I no longer have a V3.2.7 test environment, so I cannot say if the bug manifests on previous versions.

**Comment by 3D-I** [comment]
I am doing some test for this so that's just a test:

OPEN `ROOT\ext\phpbbstudio\tcs\event\setup_listener.php`

FIND at line 36 
`'core.viewforum_modify_sort_direction'				=> 'tcs_viewforum_modify_sort_direction',`

REPLACE WITH
`//'core.viewforum_modify_sort_direction'				=> 'tcs_viewforum_modify_sort_direction',`

So that the line is commented out, now go to ACP and purge the cache.
